# --------------------------
# ConfigMap - nginx.conf
# --------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: task-manager
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;
        
        upstream user_service {
            server user-service.task-manager.svc.cluster.local:3001;
            keepalive 32;
        }
        
        upstream task_service {
            server task-service.task-manager.svc.cluster.local:5000;
            keepalive 32;
        }
        
        upstream frontend {
            server frontend.task-manager.svc.cluster.local:3000;
            keepalive 32;
        }
        
        server {
            listen 8080;
            server_name _;
            
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            
            location /api/v1/auth/ {
                limit_req zone=login burst=10 nodelay;
                proxy_pass http://user_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            location /api/v1/users/ {
                limit_req zone=api burst=20 nodelay;
                proxy_pass http://user_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            location /api/v1/tasks/ {
                limit_req zone=api burst=50 nodelay;
                proxy_pass http://task_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }

---
# --------------------------
# Deployment - API Gateway
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: task-manager
spec:
  replicas: 1 # keep cost low for demo
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: task-manager
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
