apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway.yaml
- configmap.yaml
- frontend.yaml
- hpa.yaml
- ingress.yaml
- namespace.yaml
- postgres.yaml
- secrets.yaml
- task-service.yaml
- user-service.yaml