apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: task-manager
type: Opaque
stringData:
  JWT_SECRET: "HhY4Lp1sYtD9hN/8QqP9MffV8A8nG4I8OayhYpztq6E="
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  DB_USER: "dbadmin"
  DB_PASSWORD: "SecurePassword123!"
  DATABASE_URL: "postgresql://dbadmin:SecurePassword123!@postgres:5432/taskmanager"
